import "@/styles/globals.css";
import Head from "next/head";
import Header from "./header";

export default function App({ Component, pageProps }) {
  return (

    <>

    {/* head */}
      <Head>
        <title>Pay Procc</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.ico" />

      </Head>

      {/* main body  */}
      <Header />
      <Component {...pageProps} />
    </>
  );
}
